name: Run examples

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy flake8 pycodestyle pytest nbval pandas matplotlib scikit-learn
        pip install -r backend/requirements.txt
    - name: Running notebooks with examples
      env:
        PYTHONPATH: backend/app/models/som/vendor
        EXAMPLES: backend/app/models/som/examples
      run: |
        pytest --nbval-lax "$EXAMPLES"/BasicUsage.ipynb
        pytest --nbval-lax "$EXAMPLES"/Clustering.ipynb
        pytest --nbval-lax "$EXAMPLES"/Classification.ipynb
        pytest --nbval-lax "$EXAMPLES"/ColorQuantization.ipynb
        pytest --nbval-lax "$EXAMPLES"/ColorSpaceMapping.ipynb
        pytest --nbval-lax "$EXAMPLES"/OutliersDetection.ipynb
        pytest --nbval-lax "$EXAMPLES"/HexagonalTopology.ipynb
        # pytest --nbval-lax "$EXAMPLES"/TopicModeling.ipynb
        pytest --nbval-lax "$EXAMPLES"/DemocracyIndex.ipynb
